name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install project dependencies
        run: poetry install

      - name: Build and publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_PASSWORD }}
          poetry build
          poetry publish
